[package]
name = "spectrogram-3d"
version = "0.1.0"
authors = ["Leo Conrad-Shah <leoconr@nuevaschool.org"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num = "0.2.0"
stdweb = "0.4.17"
